### PR TITLE
Fix number of days feature

### PR DESCRIPTION
**Pull request by timjkong**

### CODE REVIEW

**Review by jeannetoh99 — APPROVED** [review]
LGTM

**Review by lyeyixian — APPROVED** [review]
LGTM. But I don't know if this overlaps with what Jiawei has done

**Comment by jiaweiteo** [comment]
> LGTM. But I don't know if this overlaps with what Jiawei has done

I think we can use Tim's method instead. Better abstraction. Tim, you can resolve the conflicts and merge

**Review by jiaweiteo — APPROVED** [review]
LGTM

**Pull request closed without merging**
